attendance-app/attendance_app/attendance_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from home import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'))),
    path('user/', include(('user.urls', 'user'))),
    path('course/', include(('course.urls', 'course'))),
    path('survey/', include(('survey.urls', 'survey')))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

attendance-app/attendance_app/home/urls.py
from django.urls import path, include
from home import views

from django.contrib.auth import views as auth_views
from home.forms import CustomAuthenticationForm


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html', authentication_form=CustomAuthenticationForm), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

attendance-app/attendance_app/survey/urls.py
from django.urls import path, include
from survey import views


app_name = 'survey'

urlpatterns = [
    path('', views.survey_division_list, name='survey_division_list'),
    path('course_survey/<int:pk>', views.survey_list, name='survey_list'),
    path('detail/<int:pk>/', views.survey_detail, name='survey_detail'),
    path('reply_detail/<int:pk>/', views.survey_reply_detail, name='survey_reply_detail'),
    
    # 설문 목록 다운로드
    path('download/<int:pk>/', views.download_surveyreply, name='download_surveyreply'),
    
    
    # 학생 설문 페이지 
    path('survey_student_reply/<int:pk>/', views.survey_student_reply, name='survey_student_reply'),
    path('survey_student_submit/', views.survey_student_submit, name='survey_student_submit'),
    
    # path('create/', views.create_course, name='create_course'),
    # path('edit/<int:pk>/', views.edit_course, name='edit_course'),
    # path('delete/<int:pk>/', views.delete_course, name='delete_course'),
]

attendance-app/attendance_app/home/models.py
from django.db import models

# Create your models here.

attendance-app/attendance_app/home/forms.py
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthenticationForm(AuthenticationForm):
    error_messages = {
        'invalid_login': '잘못된 사용자명 또는 비밀번호입니다.',
        'inactive': '비활성화된 계정입니다.',
    }

attendance-app/attendance_app/home/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render

# Create your views here.
def home(request):
    
    return render(request, 'home/home.html')

attendance-app/attendance_app/home/templates/home/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
      .btn {
        height: 300px;
        display: flex;
        align-items: center;
        text-align: center;
        justify-content: center;
      }

      .btn-text {
        font-size: 61px; 

      }

      .text-container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100%;
      }
    </style>

    <title>Home</title>

</head>
<body>
  {% include 'home/navbar.html' %}

  <div class="container">

    

    {% if user.is_authenticated %}
      <!-- 관리자일 때, -->
      {% if user.is_staff %}
      <br><br><br><br>
      <div class="btn-div d-grid gap-2">
        <a role="button" class="btn btn-secondary" type="button" href="{% url 'user:admin_home' %}">
          <div class="text-container">
            <span class="btn-text"><b>관리자 페이지로</b></span>
          </div>
        </a>
      </div>

      <!-- 학생일 때, -->
      {% else %}
      <p>현재 수강중인 과목</p>
      <h3>
        <b>
          {{user.student.current_course_name}}
        </b>
      </h3>
      <br>
      <div class="btn-div d-grid gap-2 ">
        <a role="button" class="btn btn-success" type="button" href="{% url 'user:show_in_qr' %}">
          <div class="text-container">
            <span class="btn-text"><b>입실</b></span>
          </div>
        </a>
        {% if user.student.current_course_name != "수강중인 강의 없음" %}
          <a role="button" class="btn btn-info" type="button" href="{% url 'survey:survey_student_reply' user.student.pk %}">
            <div class="text-container">
              <span class="btn-text"><b>퇴실</b></span>

            </div>
            
          </a>
        {% endif %}
      </div>

  
      {% endif %}
    
    <!-- 로그인을 안했을 때 -->
    {% else %}
    <br><br><br><br>
    <h1 class="text-center">
      <b>로그인 하세요</b>
    </h1>
    
    <br><br><br>

    <h3 class="text-center">
      <a href="{% url 'home:login' %}">로그인 하러가기</a>
    </h3>

    <br><br>
    
    <h3 class="text-center">
      계정이 없으신가요? 만드세요! 

      <a href="{% url 'user:signup' %}">
        계정 생성
      </a>
    
    </h3>
    {% endif %}


 
  </div>

</body>
</html>

attendance-app/attendance_app/home/templates/home/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>로그인</title>
</head>
<body>
    {% include 'home/navbar.html' %}


    
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
              <div class="card">
                <div class="card-header">
                  <h4>Login</h4>
                </div>
                
                <div class="card-body">
                  {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                  {% endif %}

                  <form action="{% url 'home:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control form-control-user"
                            id="username" name="username" placeholder="아이디">
                    </div>

                    <br>
                    
                    <div class="form-group">
                        <input type="password" class="form-control form-control-user"
                            id="password" name="password" placeholder="비밀번호">
                    </div>

                    <br>

                    <button type="submit" class="btn btn-primary btn-user btn-block">로그인</button>
                    {% if error_message %}
                        <p class="error-message" style="color: red;">{{ error_message }}</p>
                    {% endif %}
                </form>


                </div>
                <div class="card-footer">
                  <p class="text-center">계정이 없으신가요? 만드세요! <a href="{% url 'user:signup' %}">계정 생성</a></p>
                </div>
              </div>
            </div>
          </div>
    </div>
</body>
</html>

attendance-app/attendance_app/home/templates/home/navbar.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<nav class="navbar navbar-expand-lg bg-body-tertiary bg-light">
  <div class="container-fluid container">
      <a class="navbar-brand" href="{% url 'home:home' %}"><b>출석 체크</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mb-3">
              {% if user.is_authenticated %}
                  {% if user.is_staff %}
                    <!-- staff한테 보여주는 내용 -->

                      <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">메인 페이지</a>
                      </li>
  
                      <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'user:admin_home' %}">관리자 페이지</a>
                      </li>
  
                      <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home:logout' %}">로그아웃</a>
                      </li>
                      
                      {% if user.student %}
                      <span class="navbar-text mr-3">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 환영합니다, <b> {{ user.student }} </b>

                      </span>
                      {% else %}
                      <span class="navbar-text mr-3">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 환영합니다, <b> {{ user }} [관리자 계정] </b>
                      </span>
                      {% endif %}
                  {% else %}
                    <!-- staff가 아닌 일반 사용자한테 보여줄 내용 -->
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">QR 출석</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:student_detail' %}">내 정보</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:student_attendance_detail' %}">내 출석</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link" aria-current="page" href="{% url 'home:logout' %}">로그아웃</a>
                    </li>
                    <!-- 환영합니다. XXX 님 보여주기 -->
                    {% if user.student %}
                    <span class="navbar-text mr-3">
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 환영합니다, <b> {{ user.student }}님 </b>
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b> {{ user.student.division }} 과정 수료중입니다.</b>
                    </span>
                    {% else %}
                    <span class="navbar-text mr-3">
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 환영합니다, <b> {{ user }} </b>
                    </span>
                    {% endif %}
                
                  {% endif %}
              {% else %}
                <!-- 로그인 안 했을 때 보여주는 내용 -->
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'home:login' %}">로그인</a>
                </li>
              {% endif %}
          </ul>
      </div>
  </div>
</nav>