attendance-app/attendance_app/attendance_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from home import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls', 'home'))),
    path('user/', include(('user.urls', 'user'))),
    path('course/', include(('course.urls', 'course'))),
    path('survey/', include(('survey.urls', 'survey')))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

attendance-app/attendance_app/course/urls.py
from django.urls import path, include
from course import views

from django.contrib.auth import views as auth_views

app_name = 'course'

urlpatterns = [
    path('<int:pk>', views.course_list, name='course_list'),
    path('detail/<int:pk>/', views.course_detail, name='course_detail'),
    

    
    path('create/', views.create_course, name='create_course'),
    path('edit/<int:pk>/', views.edit_course, name='edit_course'),
    path('delete/<int:pk>/', views.delete_course, name='delete_course'),
    path('download/<int:pk>', views.download_attendance, name='download_attendance' ),


    path('attendance_division_list/', views.attendance_divison_list, name='attendance_division_list'),
    path('attendance_course_list/<int:pk>/', views.attendance_course_list, name='attendance_course_list'),
    path('attendance_course_board/<int:pk>/', views.attendance_course_board, name='attendance_course_board'),


    path('QRScanner_in/<int:pk>/', views.QRScanner_in, name='QRScanner_in'),
    path('QRScanner_out/<int:pk>/', views.QRScanner_out, name='QRScanner_out'),
    path('attendance_check_in', views.attendance_check_in, name='attendance_check_in'),
    path('attendance_check_in_success/<int:pk>/', views.attendance_check_in_success, name='attendance_check_in_success'),
    path('attendance_check_out', views.attendance_check_out, name='attendance_check_out'),
    
    path('student_attendance_update', views.student_attendance_update, name='student_attendance_update'),

]

attendance-app/attendance_app/home/urls.py
from django.urls import path, include
from home import views

from django.contrib.auth import views as auth_views
from home.forms import CustomAuthenticationForm


app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='home/login.html', authentication_form=CustomAuthenticationForm), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

attendance-app/attendance_app/course/models.py
from django.db import models
from user.models import Student, Division

from datetime import time
# Create your models here.


# 강의
class Course(models.Model):
    course_name = models.CharField(max_length=50)
    teacher_name = models.CharField(max_length=20)
    division_name = models.ForeignKey(Division, on_delete=models.CASCADE)
    start_date = models.DateField()
    start_at = models.TimeField()
    end_at = models.TimeField()
    hours = models.IntegerField()
    
    def __str__(self):
        return f'[{self.division_name}] {self.course_name} (강사: {self.teacher_name}) - 수업시간: {self.hours}'



# 강의에 대한 학생 출석
class ClassAttend(models.Model):
    course_id = models.ForeignKey(Course, on_delete=models.CASCADE)
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    start_at = models.TimeField(default=time(0, 0))
    end_at = models.TimeField(default=time(0, 0))

    attend_state = models.IntegerField(default=0)   # --> 2(출석) 1(지각) 0(결석)
    # l(지각) 부분은 수업 정상 입실시간의 15분 뒤에 입실 시간이 찍히면(비교), 지각으로 처리

    def __str__(self):
        return f'[{self.course_id.course_name} 출석] {self.student_id.name}'

attendance-app/attendance_app/course/forms.py
from django import forms
from course.models import Course, ClassAttend
from django.utils.safestring import mark_safe
from django.forms import DateInput, TimeInput


# 강의 추가 폼
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
        labels = {
            'course_name': mark_safe('<b>강의 제목</b>'),
            'teacher_name': '강사명',
            'division_name': '분반 이름',
            'start_date': '시작 날짜',
            'start_at': '시작 시간',
            'end_at': '종료 시간',
            'hours': '진행 시간(시간) - 숫자만 기입 ex) 3',
        }
        
        widgets = {
            'start_date': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'start_at': TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'end_at': TimeInput(attrs={'class': 'form-control', 'type': 'time'}),

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['division_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['teacher_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['start_date'].widget.attrs.update({'class': 'form-control'})
        self.fields['start_at'].widget.attrs.update({'class': 'form-control'})
        self.fields['end_at'].widget.attrs.update({'class': 'form-control'})
        self.fields['hours'].widget.attrs.update({'class': 'form-control'})

class ClassAttendInForm(forms.ModelForm):
    class Meta:
        model = ClassAttend
        fields = '__all__'
        exclude = ['end_at', 'submit_survey', 'attend_state']

attendance-app/attendance_app/course/views.py
import os

from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404

from course.forms import CourseForm, ClassAttendInForm
from survey.forms import SurveyForm

from course.models import Course, ClassAttend
from user.models import Division
from user.models import Student
from survey.models import SurveyReply,Survey
from django.db.models import Q

from django.contrib.auth.decorators import login_required, user_passes_test

# 엑셀 다운로드
import openpyxl
from openpyxl.utils import get_column_letter
from django.conf import settings

from datetime import datetime, timedelta
from django.http import HttpResponse



# Create your views here.

# QR코드 스캐너 & 스캔후 데이터 받아서 출결 찍기
def QRScanner_in(request, pk):
    course = get_object_or_404(Course, pk=pk)

    if request.method == 'POST' and  'data' in request.POST and request.POST.get('data') != "":
        qr_data = request.POST.get('data')
        
        try:
            student = Student.objects.get(name=qr_data)
            # user Id값이 data에 들어감
            print("url 데이터 : " + student.name)

            # 현재 시간( 년도-월-일-시각-분)
            now = datetime.now()
            time_now = now.strftime('%H:%M:%S')
                

            context = {
                'course' : course,
                'check_time' : time_now,
                'student' : student,
                'status' : True,    # 입실 -> True, 퇴실 -> False
            }
            
            # 출석체크 페이지로 이동
            return render(request, 'attendance/attendance_check.html', context)
        except Student.DoesNotExist:
            print("유효한 QR코드가 입력값으로 들어오지 않았습니다.")
            context = {
                'course' : course,
                'qr_error' : True,
                'error_message' : "유효한 QR코드가 아닙니다. 등록된 QR코드를 보여주세요"
            }
            return render(request, 'attendance/QRScanner_in.html', context)
        
    else :
        context = {
            'course' : course,
        }
        return render(request, 'attendance/QRScanner_in.html', context)


def QRScanner_out(request, pk):
    course = get_object_or_404(Course, pk=pk)

    if request.method == 'POST' and  'data' in request.POST and request.POST.get('data') != "":
        qr_data = request.POST.get('data')
        
        try:
            student = Student.objects.get(name=qr_data)
            # user Id값이 data에 들어감
            print("url 데이터 : " + student.name)

            # 현재 시간( 년도-월-일-시각-분)
            now = datetime.now()
            time_now = str(now.strftime('%Y-%m-%d %H:%M'))
                

            context = {
                'course' : course,
                'check_time' : time_now,
                'student' : student,
                'status' : False, # 입실 -> True, 퇴실 -> False
            }
            
            # 출석체크 페이지로 이동
            return render(request, 'attendance/attendance_check.html', context)
        except Student.DoesNotExist:
            print("유효한 QR코드가 입력값으로 들어오지 않았습니다.")
            context = {
                'course' : course,
                'qr_error' : True,
                'error_message' : "유효한 QR코드가 아닙니다. 등록된 QR코드를 보여주세요"
            }
            return render(request, 'attendance/QRScanner_out.html', context)
        
    else :
        context = {
            'course' : course,
        }

        return render(request, 'attendance/QRScanner_out.html', context)

### 입실,퇴실 체크 모듈에 데이터 넣기

#입실용
def attendance_check_in(request):
    if request.method == 'POST':
        print("post입력 확인")
        form = ClassAttendInForm(request.POST)
        class_attend = form.save(commit=False)
        #  출석 데이터 조회
        attend_data = ClassAttend.objects.filter(Q(course_id=class_attend.course_id) & Q(student_id=class_attend.student_id))
        
        if len(attend_data) == 0:
            # 데이터가 0개인 경우
            if form.is_valid():
                # 정상 입실 확인 / ClassAttend 객체 생성
                print("form 유효성 성공")
                classAttend = form.save()
                return redirect('course:attendance_check_in_success', pk=classAttend.pk)  # 식별자(pk)를 URL에 포함시켜 리디렉션
            else:
                errors = form.errors.as_text()
                print(errors)  # 에러 메시지 출력 또는 원하는 동작 수행
                return render(request, 'attendance/attendance_error.html', {'form': form})
        else :
            # 데이터가 1개 이상인 경우 (출입을 이미 한 경우)
            course = class_attend.course_id
            student = class_attend.student_id
            error_message = student.name + "님 이미 입실등록을 하셧습니다."
            context = {
                'course': course, 
                'error_message': error_message,
                'qr_error' : True,
            }
            return render(request, 'attendance/QRScanner_in.html', context)
    else:
        return render(request, 'attendance/attendance_error.html')

# 출석 성공 페이지
def attendance_check_in_success(request, pk):

    classAttend = ClassAttend.objects.get(pk=pk)  # 식별자(pk)를 사용하여 클래스 인스턴스 조회

    # 시간값 비교를 위한 datetime 객체로 변환. 시간값만 비교
    course_late_at = datetime.combine(datetime.min,classAttend.course_id.start_at) + timedelta(minutes=15)
    print(course_late_at)
    student_start_at = datetime.combine(datetime.min,classAttend.start_at)
    print(student_start_at)

    # 시작시간보다 15분 뒤에 입실을 할시 (지각 처리)
    if student_start_at > course_late_at :
        late_check = False
    # 시작 시간 15분 이내에 입실을 할시 (정상 출석)
    else :
        late_check = True

    course = classAttend.course_id
    student = classAttend.student_id

    # 현재 듣고있는 강의 필드에 추가
    student.current_course_name = course.course_name
    student.save()

    context =  {
        'classAttend': classAttend, 
        'course': course, 
        'student': student,
        'late_check' : late_check,
    }
    return render(request, 'attendance/attendance_check_in_success.html', context)

################################
# (미사용)퇴실용
def attendance_check_out(request):
    if request.method == 'POST':
        course_id = request.POST.get('course_id')
        student_id = request.POST.get('student_id')

        end_at = request.POST.get('end_at')
        time_string = end_at
        parsed_time = datetime.strptime(time_string, "%Y-%m-%d %H:%M")
        formatted_time = parsed_time.strftime("%H:%M")
        print(formatted_time)
        

        # 지각을해서 입실처리는 하지않고, 퇴실처리만 시도한 경우
        try : 
            classAttend = ClassAttend.objects.get(Q(course_id=course_id) & Q(student_id=student_id))
            print(classAttend)
        except :
            student = Student.objects.get(id = student_id)
            error_message = student.name + "님 입실 처리를 하셔야 퇴실 처리를 하실수 있습니다!! (지각시 관리자에게 수동 출석을 요청하세요)"
            context = {
                'course' : Course.objects.get(id = course_id),
                'error_message' : error_message,
                'qr_error' : True,
            }
            return render(request, 'attendance/QRScanner_out.html', context)            
        
        # 설문지 제출했는지 확인
        # survey_reply = SurveyReply.objects.get(Q(course_id=course_id) & Q(student_id=student_id))
        # if survey_reply.submit_survey !=True:
        #    ...
        
        ### 퇴실 예외처리 부분
        # 강의평가를 제출했는지 확인 
        survey = Survey.objects.get(course_id=classAttend.course_id)
        try :
            survey_reply = SurveyReply.objects.get(student_id=classAttend.student_id, survey_id=survey)
            # 2차 검증 (강의평가를 제출하지 않았으면)
            if survey_reply.submit_survey == False:
                course = classAttend.course_id
                student = classAttend.student_id
                error_message = student.name + "님 강의평가를 제출하지 않으셔서 퇴실처리 되지않았습니다. (강의평가 제출 후 퇴실처리 바랍니다.)"
                context = {
                    'course' : course,
                    'error_message' : error_message,
                    'qr_error' : True,
                }
                return render(request, 'attendance/QRScanner_out.html', context)            
            
        except SurveyReply.DoesNotExist : 
            # 강의평가를 제출하지 않았으면 
            course = classAttend.course_id
            student = classAttend.student_id
            error_message = student.name + "님 강의평가를 제출하지 않으셔서 퇴실처리 되지않았습니다. (강의평가 제출 후 퇴실처리 바랍니다.)"
            context = {
                'course' : course,
                'error_message' : error_message,
                'qr_error' : True,
            }
            return render(request, 'attendance/QRScanner_out.html', context)            
        
        # classAttend.attend_state(퇴실 처리를 이미 했으면)
        if classAttend.attend_state == 2:
            course = classAttend.course_id
            student = classAttend.student_id
            error_message = student.name + "님 이미 정상 퇴실처리 되셧습니다."
            context = {
                'course' : course,
                'error_message' : error_message,
                'qr_error' : True,
            }
            return render(request, 'attendance/QRScanner_out.html', context)            
        

        ### 정상 퇴실 처리 부분 

        # 시간값 비교를 위한 datetime 객체로 변환. 시간값만 비교
        course_late_at = datetime.combine(datetime.min,classAttend.course_id.start_at) + timedelta(minutes=15)
        print(course_late_at)
        student_start_at = datetime.combine(datetime.min,classAttend.start_at)
        print(student_start_at)

        # 시작시간보다 15분 뒤에 입실을 할시 (지각 처리)
        if student_start_at > course_late_at :
            classAttend.end_at = formatted_time
            classAttend.attend_state = 1 # 지각 출석
            classAttend.save()
        # 시작 시간 15분 이내에 입실을 할시 (정상 출석)
        else :
            classAttend.end_at = formatted_time
            classAttend.attend_state = 2 # 정상 출석
            classAttend.save()
            
        course = classAttend.course_id
        student = classAttend.student_id

        # 퇴실까지 완료하면 다시 리셋
        student.current_course_name = "수강중인 강의 없음"
        student.save()

        # 건네줄 cotext
        context = {
            'course' : course,
            'student' : student,

attendance-app/attendance_app/course/templates/attendance/QRScanner_in.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html>
<head>
  <meta charset="utf-8">
  <title>jsQR Demo</title>
  <script src="{% static 'admin/js/jsQR.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- jQuery 라이브러리 임포트 -->
  <link href="https://fonts.googleapis.com/css?family=Ropa+Sans" rel="stylesheet">
  <style>
    body {
      font-family: 'Ropa Sans', sans-serif;
      color: #333;
      max-width: 640px;
      margin: 0 auto;
      position: relative;
    }

    #githubLink {
      position: absolute;
      right: 0;
      top: 12px;
      color: #2D99FF;
    }

    h1 {
      margin: 10px 0;
      font-size: 40px;
    }

    #loadingMessage {
      text-align: center;
      padding: 40px;
      background-color: #eee;
    }

    #canvas {
      width: 100%;
    }

    #output {
      margin-top: 20px;
      background: #eee;
      padding: 10px;
      padding-bottom: 0;
    }

    #output div {
      padding-bottom: 10px;
      word-wrap: break-word;
    }

    #noQRFound {
      text-align: center;
    }

    #notification-container {
      background: rgba(255, 0, 0, 0.7);
      color: #fff;
      text-align: center;
      padding: 10px;
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      opacity: 0;
      transition: opacity 0.5s ease-in-out;
    }

    #notification-container.show {
      opacity: 1;
    }
  </style>
</head>
<body>
  <h1>전자출결 (출입용)</h1>
  <hr>
  
  <p>과목 명 : {{course.course_name}} &nbsp;&nbsp;&nbsp; 강사 : {{course.teacher_name}} </p>
  <p>수업 일시 : {{course.start_date}}</p>
  <p>수업 시작 : {{course.start_at}}  &nbsp;&nbsp;&nbsp; || &nbsp;&nbsp;&nbsp;  수업 종료 : {{course.end_at}}</p>
  <p>수업 시간 : {{course.hours}} 시간</p>

  <!-- 유효하지 않은 QR코드를 제시했을시에 뜨는 알림창-->
  <div class="notification-container" id="notification-container">
    <p id="notification-message">{{ error_message }}</p>
  </div>

  <p>학생 QR코드를 카메라에 보여주세요.</p>
  <h3>
    <a class="btn btn-warning" href="{% url 'course:course_detail' course.pk %}">
      강의 목록으로
    </a>
  </h3>
  <div id="loadingMessage">🎥 Unable to access video stream (please make sure you have a webcam enabled)</div>
  <canvas id="canvas" hidden></canvas>
  <div id="output" hidden>
    <div hidden><b>Data:</b> <span id="outputData" style="display: none;"></span></div>
    <div id="outputMessage">No QR code detected.</div>
  </div>

  <script>
    var video = document.createElement("video");
    var canvasElement = document.getElementById("canvas");
    var canvas = canvasElement.getContext("2d");
    var loadingMessage = document.getElementById("loadingMessage");
    var outputContainer = document.getElementById("output");
    var outputMessage = document.getElementById("outputMessage");
    var outputData = document.getElementById("outputData");

    function drawLine(begin, end, color) {
      canvas.beginPath();
      canvas.moveTo(begin.x, begin.y);
      canvas.lineTo(end.x, end.y);
      canvas.lineWidth = 4;
      canvas.strokeStyle = color;
      canvas.stroke();
    }

    // Use facingMode: environment to attemt to get the front camera on phones
    navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" } }).then(function(stream) {
      video.srcObject = stream;
      video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
      video.play();
      requestAnimationFrame(tick);
    });
    
    function tick() {
      loadingMessage.innerText = "⌛ Loading video..."
      if (video.readyState === video.HAVE_ENOUGH_DATA) {
        loadingMessage.hidden = true;
        canvasElement.hidden = false;
        outputContainer.hidden = false;

        canvasElement.height = video.videoHeight;
        canvasElement.width = video.videoWidth;
        canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
        var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
        var code = jsQR(imageData.data, imageData.width, imageData.height, {
          inversionAttempts: "dontInvert",
        });
        if (code) {
          drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
          drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
          drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
          drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");
          outputMessage.hidden = true;
          outputData.parentElement.hidden = false;
          outputData.innerText = code.data;
          
          if(outputMessage.hidden){
            var scannerUrl = "{% url 'course:QRScanner_in' course.pk %}"; // url
            var csrfToken = "{{ csrf_token }}";  // CSRF 토큰을 JavaScript 변수로 가져옴
            // 폼 동적 생성
            var form = document.createElement("form");
            form.method = "POST";
            form.action = scannerUrl;

            // CSRF 토큰 필드 추가
            var csrfField = document.createElement("input");
            csrfField.type = "hidden";
            csrfField.name = "csrfmiddlewaretoken";
            csrfField.value = csrfToken;
            form.appendChild(csrfField);

            // 데이터 필드 추가
            var dataField = document.createElement("input");
            dataField.type = "hidden";
            dataField.name = "data";
            dataField.value = code.data;
            form.appendChild(dataField);

            // 폼 제출
            document.body.appendChild(form);
            form.submit();
          }
        } else {
          outputMessage.hidden = false;
          outputData.parentElement.hidden = true;
        }
      }
      requestAnimationFrame(tick);
    }

    // Show notification (qr 에러 처리부분)
    const notification = document.getElementById('notification-container')

    const showNotification = () => {
      notification.classList.add('show')
      setTimeout(() => {
        notification.classList.remove('show')
      }, 5000)
    }
    
    var qr_error = {% if qr_error %}true{% else %}false{% endif %};
    // Check QR code validity
    if (qr_error) {
      showNotification();
    }
  </script> 
</body>
</html>

attendance-app/attendance_app/course/templates/attendance/attendance_check.html
{% load static %}
<head>

</head>
<body>
{% if status == True %}
<!-- 출석 처리 -->
<form id="attendanceForm" method="post" action="{% url 'course:attendance_check_in' %}">
  {% csrf_token %}
  <input type="hidden" name="course_id" value="{{ course.pk }}">
  <input type="hidden" name="student_id" value="{{ student.pk }}">
  <input type="hidden" name="start_at" value="{{ check_time }}">
  <button type="submit">출석 처리</button>
</form>
{% else %} <!-- 이부분 수정 필요 survey 값이 참인지 알아야됌-->
<!-- 퇴실 처리 -->
<form id="attendanceForm" method="post" action="{% url 'course:attendance_check_out' %}">
  {% csrf_token %}
  <input type="hidden" name="course_id" value="{{ course.pk }}">
  <input type="hidden" name="student_id" value="{{ student.pk }}">
  <input type="hidden" name="end_at" value="{{ check_time }}">
  <button type="submit">퇴실 처리</button>
</form>
{% endif %}
<script>
  // form 자동 제출
  document.getElementById('attendanceForm').submit();
</script>
</body>

attendance-app/attendance_app/course/templates/attendance/attendance_check_in_success.html
{% load static %}
<head>

</head>
<body>
<div>{{student.name}}님</div>
{% if late_check == True %}
<p style="color: green;">정상 입실 </p>
<div>처리 되었습니다.</div>
<div>출입 시간 : {{classAttend.start_at}}</div>
{% else %}
<p style="color: red;">지각 입실 </p>
<div>처리 되었습니다.</div>
<div>출입 시간 : {{classAttend.start_at}}</div>
{% endif %}
<div id="timer"></div>

</body>
<script>
    var countdown = 5; // 시작 카운트다운 값
    var timerElement = document.getElementById('timer');
    var status = {% if status %}true{% else %}false{% endif %};

    function updateTimer() {
        timerElement.innerText = countdown;
        countdown--;

        if (countdown < 0) {
            var redirectUrl = "{% url 'course:QRScanner_in' course.pk %}";
            window.location.href = redirectUrl; // 이동할 페이지의 URL
        } else {
        setTimeout(updateTimer, 1000);
        }
    }

    updateTimer();
</script>

attendance-app/attendance_app/course/templates/attendance/attendance_check_out.html
{% load static %}
<head>

</head>
<body>
<div>{{student.name}}님</div>
<div>정상 퇴실 처리 되었습니다.</div>
<div>수고하셧습니다.</div>
<div>퇴실 시간 : {{classAttend.end_at}}</div>
<div id="timer"></div>
    
</body>
<script>
    var countdown = 5; // 시작 카운트다운 값
    var timerElement = document.getElementById('timer');
    var status = {% if status %}true{% else %}false{% endif %};

    function updateTimer() {
        timerElement.innerText = countdown;
        countdown--;

        if (countdown < 0) {
            var redirectUrl = "{% url 'course:QRScanner_out' course.pk %}";
            window.location.href = redirectUrl; // 이동할 페이지의 URL
        } else {
        setTimeout(updateTimer, 1000);
        }
    }

    updateTimer();
</script>

attendance-app/attendance_app/course/templates/attendance/attendance_error.html
출석 과정에서 오류가 발생했습니다. 관리자에게 문의 바랍니다.